version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3.8.2-management
        hostname: rabbitmq
        container_name: rabbitmq-container
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - 15672:15672
            - 5672:5672